[JENKINS-42849] add BranchProperty to assign ownership to branch jobs
jenkinsci/ownership-plugin pull request #63
Opened 2017-05-07 21:55 UTC by jordancoll

2017-05-13 11:15 UTC, oleg-nenashev requested changes
First wave of comments. Ideally it needs a bunch of tests proving the change won't cause regressions in multi-branch projects by default

2017-05-13 11:15 UTC, oleg-nenashev commented on src/main/java/org/jenkinsci/plugins/ownership/model/branches/BranchNameOwnershipStrategy.java
> +        this.pattern = Pattern.compile(pattern);
This constructor is a part of public API, but it will throw runtime exception in the case of wrong regexp. It needs to be documented

2017-05-13 11:15 UTC, oleg-nenashev commented on src/main/java/org/jenkinsci/plugins/ownership/model/branches/BranchNameOwnershipStrategy.java
> +            return "By branch name";
Ideally it should be a localizable string coming from resources

2017-05-13 11:15 UTC, oleg-nenashev commented on src/main/java/org/jenkinsci/plugins/ownership/model/branches/BranchNameOwnershipStrategy.java
> +        public FormValidation doCheckPattern(@QueryParameter String value) {
Such API methods should be `@Restricted(NoExternalUse.class)`

2017-05-13 11:15 UTC, oleg-nenashev commented on src/main/java/org/jenkinsci/plugins/ownership/model/branches/BranchNameOwnershipStrategy.java
> +        public FormValidation doCheckOwnerExpression(@QueryParameter String value) {
same

2017-05-13 11:15 UTC, oleg-nenashev commented on src/main/java/org/jenkinsci/plugins/ownership/model/branches/BranchOwnershipStrategy.java
> +    @Nullable
It should be `@CheckForNull`, Nullable does not enforce static checks

2017-05-13 11:15 UTC, oleg-nenashev commented on src/main/java/org/jenkinsci/plugins/ownership/model/branches/FromScmOwnershipStrategy.java
> +public class FromScmOwnershipStrategy extends BranchOwnershipStrategy {
FromScmBranchOwnershipStrategy, just to avoid possible confusion

2017-05-13 11:15 UTC, oleg-nenashev commented on src/main/java/org/jenkinsci/plugins/ownership/model/branches/FromScmOwnershipStrategy.java
> +            return "From scm";
needs to be localizable

2017-05-13 11:15 UTC, oleg-nenashev commented on src/main/java/org/jenkinsci/plugins/ownership/model/branches/OwnershipBranchProperty.java
> +import hudson.model.*;
Please avoid bulk imports in the main code part.

2017-05-13 11:15 UTC, oleg-nenashev commented on src/main/java/org/jenkinsci/plugins/ownership/model/branches/OwnershipBranchProperty.java
> +                    String owner = prospectiveOwner != null ? prospectiveOwner : fallbackOwner;
So you do not try job/folder ownership?

2017-05-14 22:23 UTC, jordancoll commented on src/main/java/org/jenkinsci/plugins/ownership/model/branches/OwnershipBranchProperty.java
> +                    String owner = prospectiveOwner != null ? prospectiveOwner : fallbackOwner;
inherit the owner from multibranch job?
maybe we could have the fallback owner an optional setting. if unset, we fallback to inheritance of ownership according to global config.

2017-05-14 22:48 UTC, jordancoll commented
> Ideally it needs a bunch of tests proving the change won't cause regressions in multi-branch projects by default

The `BranchProperty` only affects the branches it is applied to, so I don't think there is much risk of changing existing behavior. That said, I do want to add tests. 

Is there a way to reuse `branch-api`'s [test harness](https://github.com/jenkinsci/branch-api-plugin/tree/master/src/test/java/jenkins/branch/harness) here? Or do I need to make my own?

2017-05-31 09:35 UTC, oleg-nenashev commented
Sorry, missed the update

2017-06-27 17:07 UTC, oleg-nenashev requested changes
The code looks better, some minor comments.

I think there should be the default `SameAsParentBranchOwnershipStrategy` which just falls back to the original logic.

Do you also plan to create tests for the new functionality?

2017-06-27 17:07 UTC, oleg-nenashev commented on src/main/java/org/jenkinsci/plugins/ownership/model/branches/BranchNameOwnershipStrategy.java
> +        this.ownerExpression = ownerExpression;
fix empty and trim here as well? Then you can make this field `@CheckForNull`

2017-06-27 17:07 UTC, oleg-nenashev commented on pom.xml
> +            <type>jar</type>
Better to remove explicit `jar` requirement. It may become `hpi` at some point

2017-06-27 17:07 UTC, oleg-nenashev commented on src/main/java/org/jenkinsci/plugins/ownership/model/branches/BranchNameOwnershipStrategy.java
> +        Matcher matcher = pattern.matcher(branch.getName());
No PatternSyntaxException handling. It would be better to catch it here just in case (e.g. manual config edits on the disk)

2017-06-27 17:07 UTC, oleg-nenashev commented on src/main/java/org/jenkinsci/plugins/ownership/model/branches/BranchNameOwnershipStrategy.java
> +    private Pattern pattern;
Are you sure it will be persisted correctly and then recovered? I have some doubts about it, config roundtrip tests would be useful

2017-06-27 17:07 UTC, oleg-nenashev commented on src/main/java/org/jenkinsci/plugins/ownership/model/branches/OwnershipBranchProperty.java
> +        this.fallbackOwner = fallbackOwner;
fixEmptyAndTrim()? Null would be better

2017-06-27 17:07 UTC, oleg-nenashev commented on src/main/java/org/jenkinsci/plugins/ownership/model/branches/OwnershipBranchProperty.java
> +                        // TODO: handle somehow
handle what?

2018-06-16 20:52 UTC, ssbarnea commented
@jordancoll please fix it or close the PR.

2018-06-18 13:24 UTC, oleg-nenashev commented
I would prefer to keep it open so that anybody could pick it up and finalize.
@ssbarnea I kindly ask to avoid making such requests in repositories you do not maintain. Asking for updates is fine, asking to "fix or close" is not fine

2026-07-21 13:22 UTC, atai commented
## Closing as stale

Thank you for the contribution — the use case is still valid, but this PR itself is no longer mergeable as-is.

### Verdict
- **This PR / 2017 patch:** not current — do not merge or rebase “as is”
- **The idea (JENKINS-42849):** still makes sense — Multibranch fine-grained / auto ownership remains a documented gap
- **Recommendation:** close this PR; if revisited, redesign from scratch rather than revive this branch

### Why the patch is obsolete
- ~9 years idle; last activity mid-2018; `CHANGES_REQUESTED` were never fully addressed (tests, `SameAsParentBranchOwnershipStrategy` / inheritance fallback, etc.)
- Stack is far behind current plugin baselines (today: Jenkins 2.479.x + BOM; this PR pinned ancient `branch-api` / folder versions; `branch-api` is not even a dependency in current `pom.xml`)
- Fragile bits in the old code (Pattern persistence/roundtrip, User lookup APIs, incomplete IOException handling, required fallback instead of folder inheritance)

### Why the idea still matters
Docs still say Multibranch ownership is only manageable at the top level, and fine-grain per-branch ownership is unsupported. Partial workarounds exist (folder inheritance, `AssignCreatorPolicy`, Jenkinsfile `JobOwnerJobProperty`), but they do not cover discovery-time assignment from SCM contributor / branch-name strategies that this PR aimed for. [JENKINS-42849](https://issues.jenkins.io/browse/JENKINS-42849) remains open.

### If someone picks this up later
Please open a **new** PR with a modern design: optional `branch-api` via BOM, inherit/same-as-parent as the default for compatibility, From-SCM (and optionally by-branch-name) strategies, Multibranch tests, and an update to `doc/PipelineIntegration.md`. Cherry-picking this 2017 branch is not recommended.

Closing to reduce stale open-PR noise; the feature request can live on via JENKINS-42849 (or a fresh GitHub issue).

2026-07-21 13:22 UTC, closed without merging